version: '3.1'

services:
  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${ROOT_PASSWORD_DB} 
      MYSQL_DATABASE: ${NAME_DB}                
      MYSQL_USER: ${USERNAME_DB}               
      MYSQL_PASSWORD: ${PASSWORD_DB}          
    ports:
      - "${PORT_DB}:${PORT_DB}"                
    volumes:
      - db_data:/var/lib/mysql                   

  redis:
    image: redis:latest
    container_name: my_redis
    ports:
      - "6379:6379"                              
    volumes:
      - redis_data:/data                         

  mongo:
    image: mongo:latest
    container_name: my_mongo
    ports:
      - "27017:27017"                            
    volumes:
      - mongo_data:/data/db                     

volumes:
  db_data:
  redis_data:
  mongo_data:
